### ISSUE TITLE
1.0 Roadmap discussion

### ISSUE THREAD

**Issue by nicolas-zozol** [masala/masala-parser#42]
Suppose there is no bug. What feature do we need for 1.0 ? 

* Kiss compiler
* Clear separation of concerns:
   * Use of Bundles #52
    * isolated libs in standard 
    * examples in examples
* Good naming
* Dealing with internationalization : #51
* Compatible with Fantasy Land library for monadic support
* Build a pattern matching library on top of parsec
* Binary stream decoder (Scala Scodec)
* Data Marshaller based on binary stream decoder

Any ideas ?

**Comment by ccorcos** [comment]
hey guys, so I've built my own mini parser library and I'm actually surprised to see how similar they are at this point -- I find it a lot easier to understand what you guys are doing here now. but take a look:

https://gist.github.com/ccorcos/ae60844a5a8fa0c5df86641ba45b7c4c

Some suggestions based on comparing these libraries:

- simplify. 
  - it looks like ive produces all of the core functionality in about ~100 lines of code and all of the core combinators in another ~100 lines.
  - i find it easier to understand if all the prototype methods were stripped down the bare minimum. Things like `map`, `chain`, `fold` and stuff like that. `or`, `rep`, `thenLeft` and all that is just distracting to me and seems to bloat  a very simple data type.
  - im not sure if its entirely kosher but passing the stream as a second argument to Response.chain makes Parser.chain a lot cleaning. `bindAccepted` doesnt feel right.
  - all of the stream classes seem unnecessary.
- reorganize
  - I like how bennu organizes things. `Parser`, `Stream` and `Response` are basically the three core data types. Then there are fundamental combinators: always, never, any, either, maybe, sequence, zeroOrMore, where, whereEq, etc. Then there are more specific parsers like char, string, digit etc. I think reorganizing like this would provide a lot of clarity for someone less familiar with this library who's reading through the source code. I guess my point is to minimize the file dependency graph. If you put Parser, Stream, and Response in a single file, you wouldnt have to import anything. If you put the combinators in another file, it only has to import the the core data types. And if you put the parser in its own file, it only has to import the combinators.

One thing I've been trying to get a better understanding of is how userState works within Bennu and Haskell's Parsec and how exactly that's useful. Its seems to be like userState only occludes logic that you could do in other ways. But its intriguing nevertheless. Maybe I just dont get it yet.

Cheers!

chet

**Comment by nicolas-zozol** [comment]
Thanx for your work. I think there is a consensus to say that there is a lot of functions in Parser. Maybe not too much, but we must definitively not add more. There is for exemple a discussion to remove flattenDeep().

We also had discussion between exporting a class of a standard JS object.

Do you have some working exemples /unit-tests of how you handle these exports ?

**Comment by nicolas-zozol** [comment]
I think we can break the Parser file in 4 bundles, each is a class that can be extended because users will use it in a very large spectrum of context.

```
class Parser{} // stays the same, without flattenDeep and maybe others

class Flux{
	
   sequence,
   lazy,
   returns,
    error,
    eos,
    sequence
}

class Chars{
	lowerCase,
    upperCase,
    digit,  // monoid value is a JS String
    number, // valuing a String
    letter,
    letters,
    notChar,
    char,
    charIn,
    charNotIn,
    string,
    notString,
    charLiteral,
    stringLiteral,
    // adding
    stringIn,
    stringNotIn
}

class Numbers{
	digit, // 
	number, // same that Chars, but returning a JS value
	numberLiteral: numberLiteral(),	
	roman // for exemple converting XXI as 21 ...
}

// then
import {P, C, N} from Parsec

C.string("doe").or(N.digit()).parse("....")

```

We have plenty of Unit tests, I'm not at all afraid to do this next week.

**Comment by ccorcos** [comment]
> We also had discussion between exporting a class of a standard JS object.

> Do you have some working exemples /unit-tests of how you handle these exports ?

Not sure I understand what you mean

**Comment by nicolas-zozol** [comment]
I had misunderstood your first message. You can discard this.

**Comment by ccorcos** [comment]
Any ideas how you plan on handling tail call optimization?

**Comment by d-plaindoux** [comment]
Well optional, repeatable and occurrence are implemented by a loop. This is a trivial kind of optimisation (not satisfactory IMHO). In general a trampoline is the best approach but it requires a complete re-design [1] since parsers are transparently called ! This can be really great. 

[1] http://www.cs.uwm.edu/~dspiewak/papers/generalized-parser-combinators.pdf

**Comment by ccorcos** [comment]
> In general a trampoline is the best approach but it requires a complete re-design [1][2] since parsers are implicitly chained by the function composition!

Exactly! Bennu has an interesting approach here. Every parser just uses this `unparser` function:

https://github.com/mattbierner/bennu/blob/4e7235d2fb2d5fe9f4bd1311616d0134a5ff0b2c/lib/parse.kep#L506-L507

And then they have a while loop to unwrap everything.

https://github.com/mattbierner/bennu/blob/4e7235d2fb2d5fe9f4bd1311616d0134a5ff0b2c/lib/parse.kep#L140-L145

Check out how they implement bind:

https://github.com/mattbierner/bennu/blob/4e7235d2fb2d5fe9f4bd1311616d0134a5ff0b2c/lib/parse.kep#L596-L604

The weird thing about their approach is that the stack keep growing, as it should since its all function composition, but when its evaluated, its just evaluated one step at a time in a while loop. Its bizarre to me that's solves the issue, lol

**Comment by nicolas-zozol** [comment]
1.0 released 3 years later :smile:
